const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Validate environment variables
const accountSid = process.env.TWILIO_ACCOUNT_SID;
const authToken = process.env.TWILIO_AUTH_TOKEN;

if (!accountSid || !authToken) {
    console.warn('Warning: Twilio credentials not found in environment variables.');
    console.warn('Please ensure you have set TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN in your .env file or GitHub secrets.');
}

// Create config.js with environment variables
const configContent = `/**
 * Configuration file for Phone Lookie
 * 
 * This file is automatically generated during:
 * - Local development: from .env file
 * - Production build: from GitHub Actions secrets
 * 
 * DO NOT manually edit this file as it will be overwritten
 */

const config = {
    TWILIO_ACCOUNT_SID: '${accountSid || ''}', // Your Twilio Account SID
    TWILIO_AUTH_TOKEN: '${authToken || ''}'    // Your Twilio Auth Token
};`;

// Ensure the js directory exists
const jsDir = path.join(__dirname, '..', 'js');
if (!fs.existsSync(jsDir)) {
    fs.mkdirSync(jsDir, { recursive: true });
}

// Write the config file
fs.writeFileSync(path.join(jsDir, 'config.js'), configContent);

console.log('Environment configuration completed');
if (!accountSid || !authToken) {
    console.log('Note: Running without Twilio credentials. The lookup feature will not work.');
} 